vect1 = c(4,9,8,2)
vect2 = c(2,3,1,7)
vect3 = c(8,3,5,4)
mat1 = rbind(vect1, vect2, vect3)
apply(as.matrix(mat1),1,max)
apply(mat1,2,max)
apply(mat1,1,cumsum)
t(apply(mat1,1,cumsum))
lapply(mat1[2,], factorial)
unlist(lapply(mat1[2,], factorial))
sapply(mat1[2,], factorial)
head(iris)
str(iris)
levels(iris$Species)
tapply(iris$Sepal.Width,iris$Species,mean)
