library(readxl)
df_IBM = read_excel('1.xlsx', sheet = 'IBM')
df_infy = read_excel('1.xlsx', sheet = 'Infosys')
df_flight  = read_excel('/home/eshaanjoshi/Desktop/flight_status.xlsx')
df_IBM_new = read_excel('1.xlsx',sheet = 'IBM', range = 'A1:D5')
df_IBM_newer = read_excel('1.xlsx', sheet = 'IBM', n_max = 3)
df_IBM_more_new = read_excel('1.xlsx',sheet = 'IBM', skip = 2)
read.table(file = 'clipboard', sep = '\t', header = FALSE)
df_IBM_more_newer = read_excel('1.xlsx', sheet = 'IBM', na = '---')
df_IBM_latest = subset(df_IBM_more_newer,df_IBM_more_newer$Salary > 250)
write_xlsx(df_IBM_latest,'2.xlsx')
write_xlsx(df_IBM_latest,'3.xlsx',col_name = FALSE)
