library(readr)
df = read_delim('employees.txt',delim = ',')
df_but_semicolon = read_delim('employees.txt',delim = ';')
df_but_tab = read_delim('employees.txt',delim = '\t')
df_wrong = read_delim('employees.txt',delim = ',')
df_wrong_but_correct_now = read_delim('employees.txt',delim = ',', trim_ws = TRUE)
df_but_no_columnname = read_delim('employees.txt',delim = ',')
df_but_no_columnname_fixed_kindof = read_delim('employees.txt',delim = ',',col_names = FALSE)
t(df)
df_missing_values = read_delim('employees.txt',delim = ',',na = c('null','',' '))
df_but_table_bec_space_delm = read_table2('employees.txt')
head(iris)
write.table(iris,file = 'iris.txt',sep = ',',)
# write.table but no index
write.table(iris,file = 'iris_no_index.txt',sep = ',',row.names = FALSE)
df_but_csv = read.csv('emp.csv',sep = ',')
# why sep ',' if csv is separated by commas
df_csv_no_header_infile = read.csv('emp.csv',header = FALSE)
write.csv(mtcars,'not_mycars.csv')
